// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jchrkbdmidyjnrpiaulo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjaHJrYmRtaWR5am5ycGlhdWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTM1NDYsImV4cCI6MjA2MDkyOTU0Nn0.B7WAUizJ0ikOyFpHzFGxvElyL9sCJ8jniQNpKs9wOFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);